name: NodeJS with Grunt

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.19.2]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Build
        run: |
          npm install
      - name: Test
        id: test-app
        run: |
          npm run test-api

      - name: Upload report
        uses: actions/upload-artifact@v2
        with:
          name: cucumber report
          path: test/reports
      - name: action-slack
        if: failure() && steps.test-app.outcome != 'success'
        uses: actions/upload-artifact@v2
        with:
          name: cucumber report
          path: /home/runner/work/test/reports
